# Generated by Django 4.1.3 on 2023-09-26 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(help_text='Напишите ФИО', max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию заявки', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', models.TextField(max_length=400, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='img', verbose_name='Картинка')),
                ('ready_design', models.ImageField(blank=True, null=True, upload_to='design', verbose_name='Готовый дизайн')),
                ('date', models.DateField(default=datetime.datetime(2023, 9, 26, 21, 33, 52, 991709))),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('load', 'Принято в работу'), ('ready', 'Выполнено')], default='new', help_text='Статус', max_length=30, verbose_name='Статус')),
                ('category', models.CharField(choices=[('sketch', 'Эскизный проект'), ('mid_detail', 'Средняя детализация'), ('author', 'Авторский интерьер')], default='Эскизный проект', help_text='Категории', max_length=30, verbose_name='Категории')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
