# Generated by Django 4.1.3 on 2023-09-26 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 22, 12, 54, 531616)),
        ),
    ]
